### ISSUE TITLE
Set custom url doesn't seem to work

### ISSUE THREAD

**Issue by AdamSGit** [AmazingDreams/vue-matomo#97]
Hello, 

I have urls with route params following this pattern : 
- `https://example.com/url/to/the/page/a993febc76a993febc76`
- `https://example.com/url/to/the/page/febc76a993febc76febce`

I want to group them in matomo report as follow : 
`https://example.com/url/to/the/page`

So I tried to use the setCustomUrl options in the router `beforeeach` hook, as follow : 
`window._paq && window._paq.push(['setCustomUrl', filteredUrl])`

It doesn't seem to work, as I see all the differents urls in matomo report. Something weird is that in the network tab of debugging tools, I see two requests. Both seem to be pageview. The first has the filtered URL, and the other the full one. I'm not sure if the two pageviews are taken into account but I can't be sure. 

Any clue on this ?
Thanks

**Comment by AmazingDreams** [comment]
Hi, 

Due to Vue being an SPA this plugin uses the custom url to set the page url. Otherwise it would always be the url used on first page load. 

Though I realise now this isn't properly documented, you can use a route `meta.title` to set a page name, similar to `meta.analyticsIgnore`

https://github.com/AmazingDreams/vue-matomo#ignoring-routes

Let me know if this helps or not

**Comment by AdamSGit** [comment]
Well, I think it could work to ignore route and track it with custom url in `beforeeach` hook. So this issue can be closed. I will let you know if it doesn't work for some reasons.

Thanks
